### ISSUE TITLE
Implement hotfix for depletion of homozygous alternate genotypes in subset code

### ISSUE THREAD

**Issue by jkgoodrich** [broadinstitute/gnomad_qc#108]
Hot fix code will also need to be added to subset scripts that include genotype information

**Comment by gtiao** [comment]
Please paste the solution that Julia coded that will be in the following PR: https://github.com/broadinstitute/gnomad_qc/pull/112

This should be a relatively quick piece of work, but we need to do this separately for the subsetting code
