### ISSUE TITLE
Further assessment of RF for a v3.1.1 release

### ISSUE THREAD

**Issue by jkgoodrich** [broadinstitute/gnomad_qc#132]

**Comment by jkgoodrich** [comment]
Trying out new binning code on one of the random forest models (3fcad4be) from v3.1. 

RF model description
```
=== 3fcad4be ===
{
    "features_importan:ce": {
        "AS_MQRankSum": 0.005873600314542055,
        "AS_QD": 0.5253868794116966,
        "AS_ReadPosRankSum": 0.03063445320910314,
        "AS_SOR": 0.19533647323827388,
        "AS_pab_max": 0.12188948966076858,
        "allele_type": 0.001754474141334427,
        "n_alt_alleles": 0.08357431037580206,
        "variant_type": 0.02473191306009187,
        "was_mixed": 0.010818406588387331
    },
    "input_args": {
        "adj": false,
        "filter_centromere_telomere": true,
        "transmitted_singletons": true,
        "vqsr_training": false
    },
    "test_accuracy": 0.9657663920980945,
    "test_intervals": "chr20"
}
INFO (gnomad.variant_qc.random_forest 590): Testing results:
rf_prediction       FP      TP
rf_label                      
FP             1078541   42611
TP               13425  502294

```

Command:
```
hailctl dataproc submit jg1 PycharmProjects/gnomad_qc/gnomad_qc/v3/variant_qc/evaluation.py --create_bin_ht  --model_id 3fcad4be
```

Job ID: ```0f48d73ab7704bbdbac01ea620950774```

**Comment by jkgoodrich** [comment]
Remaining steps for the evaluation of RF model 3fcad4be and VQSR model vqsr_alleleSpecificTrans (aggregate binned data and bin the truth sample concordance). 

Command:
```
hailctl dataproc submit jg2 PycharmProjects/gnomad_qc/gnomad_qc/v3/variant_qc/evaluation.py --create_aggregated_bin_ht  --model_id 3fcad4be
```

Job ID: ```64ad3debc9ea42db929c3b1b8897595e```



Command:
```
hailctl dataproc submit jg2 PycharmProjects/gnomad_qc/gnomad_qc/v3/variant_qc/evaluation.py --bin_truth_sample_concordance  --model_id 3fcad4be
```

Job ID: ```8dd554cee3644fce8e72ad5bd9429210```


Command:
```
hailctl dataproc submit jg1 PycharmProjects/gnomad_qc/gnomad_qc/v3/variant_qc/evaluation.py --create_aggregated_bin_ht  --bin_truth_sample_concordance --model_id vqsr_alleleSpecificTrans --overwrite
```

Job ID: ```a5606bd7f27a4069b840ca1b4e8f024a```

**Comment by jkgoodrich** [comment]
Updated variant QC notebook with fixed binning is located here: gs://gnomad/variant_qc/genomes_v3.1/variant_qc_v3.1_FINAL.ipynb

Unfortunately, we still see odd results in the random forest model when comparing to AS_VQSR on the truth datasets.

SNVs
![Screen Shot 2021-07-09 at 5.26.33 PM.png](https://images.zenhubusercontent.com/5f4d3fb5900ef2def7626452/82ed52d7-d9c6-4ad5-958f-a1fd29a374bc)

Indels:

![Screen Shot 2021-07-09 at 5.26.55 PM.png](https://images.zenhubusercontent.com/5f4d3fb5900ef2def7626452/4f96322f-5f39-4537-94c2-f2c01713144c)

**Comment by jkgoodrich** [comment]
Plots of quantitative metrics used in v3.1 RF models showing the values of SYNDIP SNVs that fell in bin 1, bins 10-12, and bin 100, and also split by TP and FPs within those bins.

The Bin 1 false positives do look like they might have some different distributions than the TPs for some metrics, for instance a bit higher AS_ReadPosRankSum, lower AS_pab_max and lower AS_QD. 

![Screen Shot 2021-07-14 at 10.21.19 AM.png](https://images.zenhubusercontent.com/5f4d3fb5900ef2def7626452/c4ea9e54-0fb5-4e99-b569-17be8e36b67e)
![Screen Shot 2021-07-14 at 10.21.04 AM.png](https://images.zenhubusercontent.com/5f4d3fb5900ef2def7626452/472842df-7230-48fc-b501-d6ed2e0c3871)
![Screen Shot 2021-07-14 at 10.20.51 AM.png](https://images.zenhubusercontent.com/5f4d3fb5900ef2def7626452/e4dcef80-291b-4a69-889c-1a6de847a85f)
![Screen Shot 2021-07-14 at 10.20.37 AM.png](https://images.zenhubusercontent.com/5f4d3fb5900ef2def7626452/a334fb72-82a0-4025-92d5-db0aa765b243)
![Screen Shot 2021-07-14 at 10.20.19 AM.png](https://images.zenhubusercontent.com/5f4d3fb5900ef2def7626452/0134a34e-62bc-45f0-9bc0-07c6618b527f)

**Comment by jkgoodrich** [comment]
Same plots but for SYNDIP indels.


![Screen Shot 2021-07-14 at 10.34.13 AM.png](https://images.zenhubusercontent.com/5f4d3fb5900ef2def7626452/d1f45e84-7963-44f0-ae0c-b8f1cfc9cafd)
![Screen Shot 2021-07-14 at 10.34.04 AM.png](https://images.zenhubusercontent.com/5f4d3fb5900ef2def7626452/02c523b8-4028-4b7e-bfc2-50435da22765)
![Screen Shot 2021-07-14 at 10.33.55 AM.png](https://images.zenhubusercontent.com/5f4d3fb5900ef2def7626452/605b3dba-73cc-4471-af30-0b06ecf580cf)
![Screen Shot 2021-07-14 at 10.33.45 AM.png](https://images.zenhubusercontent.com/5f4d3fb5900ef2def7626452/a3b36463-9b4f-44a3-8250-1f29d794070f)
![Screen Shot 2021-07-14 at 10.33.37 AM.png](https://images.zenhubusercontent.com/5f4d3fb5900ef2def7626452/22b7773c-b103-4a46-84ef-fae803ebe8ee)

**Comment by jkgoodrich** [comment]
There are several things that we can try to investigate the RF further, some that are outlined here:

https://docs.google.com/document/d/18NeDvt3VFViAj7txCDJ7ggJKlq8Mtbt547jV5J3V-80/edit

But I think further investigation on this falls more under the epic: https://app.zenhub.com/workspaces/gnomad-5f4d127ea61afc001d6be50b/issues/broadinstitute/gnomad_production/101

**Comment by gtiao** [comment]
I think it would be great to look at these plots more closely together with others (e.g., Konrad/Ben) in an ATGU/DSP meeting, but it sounds like you've reached a point at which we can reasonably stop work on the v3.1+ RF and fold in any variant QC troubleshooting and development into v4 production work. Is that how you're feeling? (I'm supportive of this move if so.)

**Comment by jkgoodrich** [comment]
Yes I think it makes sense to fold this deeper troubleshooting into v4 activities because we had already planned on making some of these changes at that point for variant QC improvements.
