### ISSUE TITLE
Metadata example

### ISSUE THREAD

**Issue by vladsavelyev** [broadinstitute/gnomad_qc#133]
Hi,

Thanks a lot for putting together this repo! I understand it's mostly aimed at building gnomAD releases, and not intended for use as-is on custom datasets. But we are starting an Australian population variation resource at the [Centre for Population Genomics](https://www.garvan.org.au/research/population-genomics), and would really appreciate using your QC approaches you as part of our pipeline. I'm currently trying to reproduce the QC tools in your repo on our data, and as far as I understand, a lot of them depend on metadata sitting in a private bucket (e.g. `gs://gnomad/metadata/genomes/gnomad.genomes.metadata.*.ht`). So I was wondering if you could share an example of that metadata, or even point to a code that can help to generate it? And are there caveats I should be aware of, and would you say it is a good idea in general to reuse your codebase for our goals?

Vlad

**Comment by ch-kr** [comment]
hi Vlad, thanks for reaching out. We realize we haven't gotten to this inquiry yet and wanted to know whether this is still relevant?

**Comment by vladsavelyev** [comment]
Not relevant. A lot of metadata was moved by gnomAD to public buckets later, and we managed to reconstruct the pipeline well. Also, I left the CPG five months ago :)
