### ISSUE TITLE
Extra readviz in gnomAD v3.1 (2 readviz with good allele balance for AC=1 variant)

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/gnomad_qc#143]
I noticed that gnomAD (v2.1 and v3) has AC = 1 (overlap/same sample) for this variant but there are 2 readviz available.
v3 https://gnomad.broadinstitute.org/variant/17-43106496-G-C?dataset=gnomad_r3 (2 readviz)

Same variant in v2.1 actually only has 1 readviz https://gnomad.broadinstitute.org/variant/17-41258513-G-C?dataset=gnomad_r2_1

both have good ABs - 44% and 52% - read data for both looks good. 

Posting just in case this ends up being connected to a larger issue down the line.

**Comment by mike-w-wilson** [comment]
The v2 sample with the variant/readviz according to v2 BigQuery is also within the v3.1 release and has readviz. v3.1 also contains a sample that was filtered from the release. I found these v3.1 samples by filtering two HTs ( gs://gnomad/readviz/genomes_v3/gnomad_v3_readviz_crams_exploded_with_key.ht and gs://gnomad-bw2/gnomad_v3_1_readviz_crams_exploded_with_key.ht to the variant. The filtered sample is from a population which was completely filtered out of gnomAD v3.1 so it should not be in the browser.
 
This metadata table, gs://gnomad-bw2/gnomad_v3.1_sample_metadata.tsv has 5 fields, `s`, `final_cram_path`, `final_crai_path`, `sex`, and `release` with a creation date of September 1st, 2020. The filtered sample's entry for `release` is `True`. The first readviz prep script has a passed arg for a metadata table and that script filters on release. I found this job from September 1st which passes that metadata file https://console.cloud.google.com/dataproc/jobs/832629adddb34219b2122efce093b5e0?region=us[…]al1&organizationId=548622027621&project=broad-mpg-gnomad . The next successful jobs run the next scripts in the readviz pipeline. `step2__rekey.py`  is run on Sept 10th. Going off of creation dates on HTs in the gnomad bucket, the v3 crams/readviz prep ran in late February so it appears that only new v3.1 samples were involved in the September readviz loading. 

Conclusion: I believe that the new v3.1 samples' crams were loaded prior to sample QC completing, which I think was sometime in mid October, and thus the metadata table was not updated with the appropriate release status and the browser's readviz contains new samples from v3.1 that are not in the release. I think this readviz bug will be most apparent when a variant was in the released data, has a low AC, and was also in a filtered but new v3.1 sample, like those from populations that were filtered in sample QC. We need @bw2 to confirm the run dates and tables used for new v3.1 sample readviz prep to confirm this as the cause of this bug.

**Comment by bw2** [comment]
I agree with Mike's conclusions. On Sept 1, I ran the 1st step in the readviz pipeline - sample selection ([readviz_prep.py](https://github.com/broadinstitute/gnomad-readviz/blob/270e981004b3c9cff0b7aa29150ffec549a247e0/readviz_prep.py) ) - 
 based on sample metadata which I received on August 31st (v3_1_new_releasable_cram_paths_with_sex.xlsx). If someone could share the up-to-date metadata table, I can work on rerunning sample selection and some of the downstream steps to so that gnomAD browser doesn't show filtered samples (& genotypes failing the AB filter).

**Comment by gtiao** [comment]
So the crucial distinction here is between "releasable" and "release". It sounds like you ran the pipeline based on samples that were "releasable" -- i.e., had permissions for release *if* they passed QC. But we only want to generate genotypes based on the actual samples in the official release. So you'll need the v3.1 release metadata table from the production team and use the field `release` to determine which samples actually passed QC and were unrelated.

**Comment by bw2** [comment]
Looking back at the August 31 thread, I saw 4445 sample ids in v3_1_new_releasable_cram_paths_with_sex.xlsx of which 4440 were in the v3.1 mt. This is a little less than the 4,454 number in https://gnomad.broadinstitute.org/blog/2020-10-gnomad-v3-1/  .  Did some samples get added to the 'release' bucket after August 31?

**Comment by gtiao** [comment]
You'll have to ping Sam about that. @mike-w-wilson may have insights as well. Good observation!

**Comment by mike-w-wilson** [comment]
hmm, I think there may be a typo in the blog post but I'm triple checking now. On Oct 2nd, we had 4445 new samples with a True releasable status.

**Comment by mike-w-wilson** [comment]
I've confirmed within the project metadata of the new samples, 4445 are releasable. There we an additional 4083 samples that flipped from unreleasable in v3 to releasable in 3.1 and also 1084 samples that flipped from releasable in v3 to unreleasable in v3.1.

**Comment by gtiao** [comment]
The blog post number of 4454 is derived from the final release sample count of 76,156 in v3.1 and the final release sample count in v3.0, which was 71,702. We can easily check the release status of each of the following from the metadata table: 4455 new samples, 4083 flipped-to-release. Remember we subtract 1084 due to removal of permissions, so it's entirely possible to account for everything, especially if you consider that many of the new samples may pass QC but be removed based on cryptic relatedness.

**Comment by nawatts** [comment]
Browser has been updated with the new readviz data.
