### ISSUE TITLE
Assess correlation of outlier metrics in v3.1

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad_qc#147]

**Comment by jkgoodrich** [comment]
This plot and code for it can be found in this HTML: gs://gnomad-julia/gnomad_v4/sample_qc_improvement_plots.html

It could use improvements visually, but wanted to put something together quickly.

![image.png](https://images.zenhubusercontent.com/5f4d3fb5900ef2def7626452/5cc35255-d423-469f-bdee-8f9b24e99b44)

**Comment by gtiao** [comment]
After this next round of plots, I'd like to get input from others in the gnomad_qc Slack channel.

**Comment by gtiao** [comment]
Based on the correlation plots for the non-residualized QC metrics, it seems like the metrics that are least tied to `n_snp` (and thus least affected by population structure) are `r_ti_tv`, `r_insertion_deletion`, and `r_het_hom_var`. I'd be curious to know how many of the HGDP samples we erroneously removed would have been retained if we only used these metrics. In general, how many samples from v3 would we have filtered if we filtered only on these three residualized metrics, compared to what we we actually did?

**Comment by jkgoodrich** [comment]
Just noticed this comment, I will get these numbers for the MPG/DSP meeting on Turesday

**Comment by jkgoodrich** [comment]
Total outliers in v3.1: 9269
Total outliers in v3.1 using 20 PCs: 8501
Total outliers with only r_ti_tv, r_insertion_deletion, r_het_hom_var: 7934
Total outliers with only r_ti_tv, r_insertion_deletion, r_het_hom_var using 20 PCs: 7225
Total outliers in v3.1 HGDP subset: 124
Total outliers in v3.1 HGDP subset using 20 PCs: 91
Total outliers in HGDP subset with only r_ti_tv, r_insertion_deletion, r_het_hom_var: 112
Total outliers in HGDP subset with only r_ti_tv, r_insertion_deletion, r_het_hom_var using 20 PCs: 69
Total outliers in v3.1 HGDP subset fully removed pops: 74
Total outliers in v3.1 HGDP subset fully removed pops using 20 PCs: 53
Total outliers in HGDP subset fully removed pops with only r_ti_tv, r_insertion_deletion, r_het_hom_var: 74
Total outliers in HGDP subset fully removed pops with only r_ti_tv, r_insertion_deletion, r_het_hom_var using 20 PCs: 37

**Comment by jkgoodrich** [comment]
Closing, will revisit if we need to. Current approach will not serve the highly diverse samples well if they have a small sample size
