### ISSUE TITLE
Try outlier detection by comparing samples against 100 nearest neighbors in PC space

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad_qc#148]

**Comment by jkgoodrich** [comment]
Posted an update to Slack: https://atgu.slack.com/archives/CRA2TKTV0/p1641919313029900

**Comment by jkgoodrich** [comment]
Notes from presenting at DSP/ATGU meeting:

- Alternative approach to identifying gnomAD sample QC outliers (to retain more underrepresented groups) (Julia)
  - Use 100 nearest neighbors in PC space as the group to compare
    - Suggestions: weighting by eigenvalue, varying number of nearest neighbors to use (50, 25/20, 10)
  - BN: complication is that samples could end up in same PC space, but actually have different ancestries
    - Not so much a problem if all PCs are weighted evenly
    - (Using 16 PCs currently)
  - JG: how to validate results?
    - KK: can start with HGDP pops
  - BN: separate indels from SNPs which should behave similarly wrt genetic ancestry, and look at degree of correlation between outlierness on indels vs. SNPs (e.g., to pinpoint general DNA degradation)

**Comment by gtiao** [comment]
To-dos:

- [ ] Vary number of nearest neighbors (50, 25, 10) and re-run analyses above
- [ ] Use HGDP pops for now to validate performance

Maybe/if needed:
- [ ] Run outlier detection on indels and SNPs separately, and measure how correlated outlier status is across SNPs and indels
- [ ] Select nearest neighbors using a weighted approach based on PC eigenvalue

**Comment by jkgoodrich** [comment]
Updates posted to this Slack thread: https://atgu.slack.com/archives/CRA2TKTV0/p1642620282000100?thread_ts=1641919313.029900&cid=CRA2TKTV0

**Comment by gtiao** [comment]
Added comments to Slack thread above with a number of observations and questions for @jkgoodrich, along with some suggestions for how we might arrive at a concrete filtering approach. Let's discuss at the next ATGU meeting.

**Comment by jkgoodrich** [comment]
**Just to keep this ticket updated, here was my response and the summary of Grace's thoughts, the updated notebooks are in the slack thread [here:](https://atgu.slack.com/archives/CRA2TKTV0/p1644896550043289?thread_ts=1641919313.029900&cid=CRA2TKTV0)**

- For The name of the HTML says "50" but the text throughout often mentions 10 nearest neighbors -- just want to confirm that this is a copy/paste error, and that the filtering in fact is 50  This was 50, it was easy to quickly change the HT used, but I had not updated all of the comments, this has now been updated in the notebook. 
- For Markdown text before cell 4 says samples that passed v3.1 outlier filter but failed nearest neighbor filtering are "FAIL OLD", but I think you mean "FAIL NEW" (and vice versa for the samples that failed v3.1 outlier filtering but passed the nearest neighbor filtering)I have changed the all notebooks to have the correct Markdown. Code is correct.
- I wasn't sure what difference, if any, there was between the table output from cell 10 and 11 Just forgot to remove the table without the _any addition at the bottom
- I can't see any distribution plots rendering for the HGDP-only analysis - I think this is fixed
- Are these meant to show just one example of a FAIL NEW Yes, I am showing only a single example of a FAIL NEW, so there certainly can be more that are also FAIL
- none of the distribution plots rendered for me I think this is fixed, but let me know if it doesn’t work

**Attached files in the Slack thread should have those fixes.**

**For the other points as a summary:**
- 10 NN distributions are too sparse to feel confident in the robustness of the outlier detection
- Maybe we should take a composite approach and only remove outliers that fail both old and new approaches (FAIL OLD and FAIL NEW hybrid)
- The patterns observed in the 50 NN for individual QC metrics remain the same -- i.e., the new methods removes fewer samples for all individual metrics except for n_singleton -- might be worth discussing at ATGU to think about why that might be the case
- Try comparing FAIL_NEW_50 and FAIL_NEW_20 in the ‘FAIL OLD and FAIL NEW hybrid’: do the outliers picked under these 2 different parameters tend to agree?
- Add n_snp:n_indel as a metric

I am currently investigating the final 2 points in the summary

**Comment by jkgoodrich** [comment]
Update and new notebooks posted here: https://atgu.slack.com/archives/CRA2TKTV0/p1649335525777529?thread_ts=1641919313.029900&cid=CRA2TKTV0

We should discuss this at the next ATGU/DSP meeting if not resolved on that thread

**Comment by gtiao** [comment]
ATGU/DSP meeting was very helpful with the following action items:

- [ ] Check that the 505 that are uniquely failing the new r_snp_indel ratio aren’t part of a single ancestry group
- [ ] Make “upset plot” to show the combinations of fail metrics (including hybrid approach)

Then after we have a look at those results, I am comfortable moving forward with a hybrid approach.

See fuller comments on Julia's latest notebook updates here: https://atgu.slack.com/archives/CRA2TKTV0/p1649871003166309?thread_ts=1641919313.029900&cid=CRA2TKTV0

**Comment by jkgoodrich** [comment]
I have added these updates to the slack channel here: https://atgu.slack.com/archives/CRA2TKTV0/p1650657413494839?thread_ts=1641919313.029900&cid=CRA2TKTV0

**Comment by gtiao** [comment]
Re-posting comments from [Slack](https://atgu.slack.com/archives/CRA2TKTV0/p1651589658466389?thread_ts=1641919313.029900&cid=CRA2TKTV0) here:

Comments on the upset plots, one by one:

- The first one establishes that there are samples failing only the old residual-based method, samples that fail only the NN-based method, and then a plurality of samples (roughly 1/3rd overall) that fail both NN and the old residual methods. The smaller combinations don't really make a difference, so those are the three main modes we appear to be dealing with. It also appears that adding the r_snp_indel metric doesn't make a huge difference to the overall proportions of samples filtered. By far the largest determinant of % filtered is the approach used.
- The second upset plot disentangles the 20 NN vs 50 NN vs. old residual results. A healthy plurality of samples are failing across the 50 NN, 20 NN, and the old residual methods; with distinct modules that describe samples failing only the old residual method, only NN (either 50 or 20), only 20 NN, and only 50 NN (listed in descending order of the number of samples filtered). Once again, the r_snp_indel metric doesn't seem to make a big difference in the number of samples filtered overall.
- The third upset plot disentangles results for using a hybrid vs. 20 NN vs. 50 NN approach. Slightly less than half of all samples will fail all three approaches; then there are distinct modules where samples fail only if NN approaches are used (either 50 or 20) or if only 20 NN is used, or if only 50 NN is used (listed in descending order of # of samples affected).

If we look at the effect of the different filtering approaches on HGDP+1KG samples, it's clear that the hybrid method does generally retain more samples, although for the SAN, there's a difference between 50 NN and 20 NN.

I would like to use a hybrid approach that uses 50 NN as a parameter, as that is the most conservative setting (least aggressive in trimming outliers). I would like to see one more upset plot, which uses that approach for filtering, and displays the different combinations of individual metrics. I suspect a lot of the individual metrics will be redundant with others, and I'm curious to see what that plot looks like.

**Comment by jkgoodrich** [comment]
I have added an update with the suggested upset plot here: https://atgu.slack.com/archives/CRA2TKTV0/p1651615266952559?thread_ts=1641919313.029900&cid=CRA2TKTV0

**Comment by gtiao** [comment]
Really beautiful work, Julia -- I'm excited about the results! I posted comments continuing in the thread here: https://atgu.slack.com/archives/CRA2TKTV0/p1651698784329319?thread_ts=1641919313.029900&cid=CRA2TKTV0

Reproducing the text below:

For the first plot, a couple comments:

- The biggest clumps of outliers are identified using the following metrics (in descending order): 1) 50NN ti/tv + 50 hybrid + old ti/tv; 2) 50NN n_singleton; 3) old het/homvar; 4) a mess of old n_del, n_ins, ins/del, n_ti, n_snp; and 5) old ti/tv
- This tells me that the biggest determinant of outlier-ness is ti/tv ratio, which has a lot of concordance across both methods (except that the old method picks a healthy number of ti/tv outliers that are only identified via the old method and not the 50NN -- hence the 5th largest stack of outliers)
- For whatever reason, 50NN picks a lot of outliers on n_singleton that the old method doesn't pick up
- The old method picks up a lot of het/homvar outliers that the 50NN doesn't pick up
- There are a bunch of samples that aren't identified via the ti/tv metric that seem to have problems with indels (and transitions and n_snp) that only the old method picks up

Most of these sets of outliers are uniquely picked up by the old method (with the exception of n_singleton outliers). It's not clear whether these are real or not, so I do want to note that if we move to the hybrid model (which really we should call an ensemble model, because we're using both methods together) we'll be making more conservative picks for our outliers and potentially missing some outliers that would have been picked in the past.

However, if we look at the plot Julia made for outliers picked by the hybrid/ensemble method, it's really quite beautiful.

- The vast majority of outliers are determined by a single metric: ti/tv ratio.
- There's a small module of outliers picked up by looking at the insertion/deletion ratio that wouldn't be picked up by ti/tv
- And there's a very small number of outliers picked up by het/homvar ratio and by n_singleton that wouldn't be picked up by those previous two metrics.
- And that's it!

Every other metric we can scrap, because the outlier-ness is concordant with one of the metrics I listed above. And by far the dominant driver of outlier-ness is ti/tv, which we've seen from the previous plot yields results that are generally concordant across methods (with a minority of samples that are ti/tv outliers only based on the regression method).

**One final circling-back analysis** we can do is to run those four metrics only (ti/tv, in/del ratio, het/homvar ratio, and n_singleton) on the 50NN and old residual methods and generate the upset plot to see exactly how many samples we'd be leaving in by imposing the "and" requirement (i.e., that samples have to fail both the 50NN and old residual method in order to be chosen as an outlier).

But my sense is that the ensemble/hybrid method using those four metrics is going to be a reasonable approach to outlier detection moving forward.

**Comment by jkgoodrich** [comment]
Full plot (after hybrid filter using the 4 metrics) without the min 10 filter

![Screen Shot 2022-05-05 at 10.20.44 AM.png](https://images.zenhubusercontent.com/5f4d3fb5900ef2def7626452/6472ea59-fdf4-4a4f-9ef5-a2a56ce42db6)
