### ISSUE TITLE
Proposed changes to sample QC for v4

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad_qc#155]
See discussion here: https://docs.google.com/document/d/1XSYWoTlS_vXEoltKo-sUpwb-jsLGz5AL_I9XDLW0a-s/edit

**Comment by jkgoodrich** [comment]
Most of the issues in this Epic are quick fixes. The one that will take longer is the [Revise sample QC outlier detection metrics to retain highly diverse samples in 1KG+HGDP](https://app.zenhub.com/workspace/o/broadinstitute/gnomad_qc/issues/154). Related to https://app.zenhub.com/workspaces/gnomad-5f4d127ea61afc001d6be50b/issues/broadinstitute/gnomad_qc/148
