### ISSUE TITLE
Cross-check AF concordance for variants in UKBB and gnomAD v4

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad_qc#157]
This is a sanity check for both sample and variant QC in v4

**Comment by nawatts** [comment]
Replaced by broadinstitute/gnomad_production#100.

**Comment by gtiao** [comment]
This hasn't been done yet -- it's a placeholder for a future action relating to QC for v4

**Comment by gtiao** [comment]
Oops, I see this was closed as a duplicate
