### ISSUE TITLE
Write gnomAD blog post about how to use 1KG+HGDP subset (to go with iPython notebook)

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad_qc#178]

**Comment by jkgoodrich** [comment]
Would be good to have Zan and Mary contribute a blog post, need to discuss with Alicia

**Comment by gtiao** [comment]
Here's the update from Alicia:

Zan and Mary from my team are leading the tutorials on HGDP+1kG. Zan presented a poster on the project at ASHG and right before that, they had gone through and parsed out who had which pieces in various scripts and those script names in the manuscript Google doc. Zan was out half this week, but they're meeting in person for a bit of a tutorial hackathon next week, so we should have a lot more to share on this front in the coming weeks.

Here's the outline doc: https://docs.google.com/document/d/1oVyJSMytaUGV_-iHJQ-n193C_hAQ5g_O6gtZHLzVsRQ/edit#heading=h.uypv336u7ngb

**Comment by gtiao** [comment]
It's unclear if we need to do this anymore. Julia has already written a blog post about the HGDP+1KG subset, and Alicia's group's notebooks will be fully commented inline in the Terra workspace.

However, since Alicia has requested that phased haplotypes for the HGDP+1KG be made available as an official gnomAD download/resource, it does make sense to create a blog post about that, for which I'll open a separate ticket

**Comment by ch-kr** [comment]
closing because this is no longer relevant
