### ISSUE TITLE
Various small tweaks to improve sanity checks

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad_qc#179]
See Slack discussion of output from v3.1.1 sanity check results: https://atgu.slack.com/archives/CNNTF8Z46/p1614708608016300?thread_ts=1614372214.004400&cid=CNNTF8Z46

- Would it be possible to add newlines after each INFO statement in the sections for raw & adj checks, sample sum checks, and the X chromosome checks (e.g., nhomalt_female == n_homalt)? It's easier to scan down for PASSED status when they're broken up by line (which is the case with most sections)

- The naming of sample sum checks is a little opaque to me: e.g., `PASSED AN-controls_and_biobanks-adj = sum(AN-adj-pop)` check -- does that mean all `AN-adj-pop` annotations were added up, or that all `AN-controls_and_biobanks-adj-pop` were added up? I think it should be the latter; same applies to all the other checks in that section

- The frequency checks section should eventually be converted into % of overall sites that don't match between the subset and the overall cohort annotations: it doesn't matter that some fraction of sites will happen, by coincidence, to have matching AN or AC between the overall cohort and the subset in question. We just want to make sure they don't match on ALL variants (otherwise we know we've done something wrong)

- `cadd.has_duplicate` is 100% False -- do we need this annotation? Is it informative in any way?

- There are also several VEP anotations that are 100% missing -- would be good eventually if we can write the code so that it automatically removes any annotation from the struct that's 100% missing (as it takes up space in both the release HT and the VCF)

**Comment by nawatts** [comment]
@mike-w-wilson was this resolved by broadinstitute/gnomad_methods#395?

**Comment by mike-w-wilson** [comment]
We've addressed bullet points 1 and 2. Bullet 3 needs to be updated but that should be a quick PR if we still want this, it's just the inverse of the current approach. Bullet 4 -- looks like this annotation was addressed and removed: https://github.com/broadinstitute/gnomad_qc/blob/0c91266eeb22d3c0c4afeffa62cdf6afbdca29d6/gnomad_qc/v3/create_release/prepare_vcf_data_release.py#L362 . Bullet 5 was not added and Grace made a new separate issue for this: https://github.com/broadinstitute/gnomad_qc/issues/186.

**Comment by jkgoodrich** [comment]
So from the comments that @mike-w-wilson made it sounds like we can close this since the one that was not addressed has a separate ticket?

**Comment by gtiao** [comment]
Yes, it sounds like we can close this ticket.
