### ISSUE TITLE
Max SNP # threshold

### ISSUE THREAD

**Issue by vladsaveliev** [broadinstitute/gnomad_qc#181]
Hi! I'm wondering how was justified the threshold of the number of autosomal SNPs of 3.75M?
https://github.com/broadinstitute/gnomad_qc/blob/2f7c6a34818bd7f4300b9d9abba5f358dde4f4f4/gnomad_qc/v3/sample_qc/sample_qc.py#L200

I see that it's mentioned the gnomAD blog posts, but couldn't find any details. Neither couldn't find details on that in the gnomAD paper supplementary (sorry if I'm missing something!).

[HGDP GVCFs](https://console.cloud.google.com/storage/browser/fc-56ac46ea-efc4-4683-b6d5-6d95bed41c5e/CCDG_14151/Project_CCDG_14151_B01_GRM_WGS.gVCF.2020-02-12/Project_CCDG_14151_B01_GRM_WGS.gVCF.2020-02-12) have ~5.2M autosomal variants per sample (per `n_snp` calculated by Hail's sample_qc on bi-allelic autosomal calls, following your pipeline), and that's even after removing low quality with ReblockGVCF before feeding the GVCFs into the combiner. So not sure what other filtering steps did I miss. Unless VQSR was applied before sample QC?

Also, I understand the number of SNPs is different in different ancestries (e.g. more in African populations). I guess that's covered by the pop-stratified filtering down further the pipeline, and the hardfilter cut-off is to remove very clear outliers?

**Comment by vladsaveliev** [comment]
Hey, just a little update to be more specific :)

The pipeline I'm using is:
1. Combine raw GVCFs with the Hail VCF combiner (driven by [this script](https://github.com/populationgenomics/joint-calling/blob/main/scripts/combine_gvcfs.py));
2. Follow [these steps](https://github.com/broadinstitute/gnomad_qc/blob/253d0a0a0f0f6bd4b166679b8579f68dbc3ed081/gnomad_qc/v3/sample_qc/sample_qc.py#L96-L124) in `sample_qc.py` from gnomad_qc (which are mimicked in this script in [our version](https://github.com/populationgenomics/joint-calling/blob/main/scripts/sample_qc.py#L296-L318) of the pipeline):
   a) Split multiallelics with `mt = hl.experimental.sparse_split_multi(mt, filter_changed_loci=True)`,
   b) Filter out the reference blocks,
   c) Filter out variants in telomeres and centromeres,
   d) Compute hail's `sample_qc()` on the bi-allelic variants (those that were assigned `was_split` in the step 2a,
   e) Apply a hard-filter to the `n_snps` value in the `sample_qc()` bi-allelic results.

Happy to prepare an executable script to reproduce on a dataproc.

I also noticed that subsetting the variants to the NA12878 high confidence regions brings the number of SNPs from ~5.2m to ~3.6m. Is there any chance that I should set `filter_lcr=True` in `filter_low_conf_regions`?

Vlad

**Comment by jkgoodrich** [comment]
Hey Vlad, we have looked this over and aside from finding a bug introduced in our code clean-up after the v3.1 release (Fixed in this PR #208, but didn't impact v3 or v3.1 numbers as described in the PR comment) we don't see any differences in the pipeline. We did not use `filter_lcr=True` in either v3 or v3.1.

Since we have both run this on the HGDP samples it might be good to compare our number on those samples directly. These numbers for our run are on this MT: gs://gcp-public-data--gnomad/release/3.1/mt/genomes/gnomad.genomes.v3.1.hgdp_1kg_subset_dense.mt MT under `sample_qc.n_snp`

**Comment by vladsaveliev** [comment]
Thanks for a reply!!

You mean the fix in #209? Makes sense!

With regards to the number of SNPs, it looks like it has to do with the fact that we deal with a much smaller dataset compared to gnomAD, and because of that the number of multi-allelic sites is smaller too. So the number of bi-allelic sites is close to the total number of sites for us, whereas in gnomAD bi-allelics are less abundant.

**Comment by jkgoodrich** [comment]
Yes the #209 fix doesn't impact your code, but we have put in the fix for future callsets. 

Yes, we also determined that the bi-allelic `n_snp` cutoff will need to be callset specific. We will add a note to the `gnomad_qc` code to help future users.

Thank you for bringing this to our attention.
