### ISSUE TITLE
Remove VEP fields that are universally missing

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad_qc#186]

**Comment by gtiao** [comment]
For v3.1, I noticed that the following VEP fields were 100% missing for all variants in the callset:
- ancestral.context
- intergenic_consequences.minimized
- motif_feature_consequences.minimized
- regulatory_feature_consequences.minimized
- transcript_consequences.minimized
- transcript_consequences.swissprot

Would it be possible for us, when we generate the VEP annotation table, to run a quick `summarize()` and flag the fields that are 100% missing and then remove them from the annotation struct *before* it's added to the release Table? This would likely save us some space, and there's no sense in keeping them around if they're universally empty

**Comment by ch-kr** [comment]
Closing; will track progress here instead https://github.com/broadinstitute/gnomad_methods/issues/476
