### ISSUE TITLE
Score bins Table for v3

### ISSUE THREAD

**Issue by vladsaveliev** [broadinstitute/gnomad_qc#192]
I can't seem to find a script that generates this resource:
https://github.com/broadinstitute/gnomad_qc/blob/253d0a0a0f0f6bd4b166679b8579f68dbc3ed081/gnomad_qc/v3/resources/variant_qc.py#L95-L112

There is a create_ranked_scores.py for v2, but it's tricky to plug it into the v3 pipeline and probably it's outdated:
https://github.com/broadinstitute/gnomad_qc/blob/master/gnomad_qc/v2/variant_qc/create_ranked_scores.py

Wondering if there was supposed to be a script analogous to create_ranked_scores.py in v3?

**Comment by jkgoodrich** [comment]
It is created in the evaluation script, we renamed some files after v2. https://github.com/broadinstitute/gnomad_qc/blob/253d0a0a0f0f6bd4b166679b8579f68dbc3ed081/gnomad_qc/v3/variant_qc/evaluation.py#L141

**Comment by jkgoodrich** [comment]
And the aggregated version is written out here: https://github.com/broadinstitute/gnomad_qc/blob/253d0a0a0f0f6bd4b166679b8579f68dbc3ed081/gnomad_qc/v3/variant_qc/evaluation.py#L170

**Comment by vladsaveliev** [comment]
Oh, thanks a lot of the pointer!! :)
