### ISSUE TITLE
Fix simultaneous homalt and het genotyping issue arising due to multi-allelic splitting followed by hotfix for depletion of homozygous alternate genotypes

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad_qc#195]
See full thread discussion here: https://atgu.slack.com/archives/CNNTF8Z46/p1620401614102100

Summary of problem written up by KC:

there is a problem with our code fix correcting the depletion of homozygous alternate genotypes (the fix is described in this blog post). in certain situations, samples that have heterozygous alternate calls at multiallelic sites may end up having both a heterozygous and a homozygous genotype at a locus after splitting multiallelics.
here’s an example (found in the 455k ukbb tranche):

chr22:19233125 has a reference allele of G and alternate alleles of A, C, GTGTGGT, and T. a sample at this site has an A/T genotype. after splitting multiallelics, we would expect that the genotypes for this sample would look like this:

chr22:19233125 G>A 0/1
chr22:19233125 G>C 0/0
chr22:19233125 G>GTGTGGT 0/0
chr22:19233125 G>T  0/1

however, it turns out that our code fix changes het genotypes with high allele balances at chr22:19233125 G>A to be homozygous alternate. thus, the genotypes for this sample actually look like this:

chr22:19233125 G>A 1/1
chr22:19233125 G>C 0/0
chr22:19233125 G>GTGTGGT 0/0
chr22:19233125 G>T 0/1

so you can see that with the code fix, this sample has both a homalt and a het call at this locus

**Comment by gtiao** [comment]
For now, we can create a genotype flag with a Boolean `is_het_non_ref` based on the raw MT before splitting, and then annotate that back onto the downstream data and re-implement the homalt depletion hotfix with a genotype-specific condition (i.e., that any genotype being reset should *not* have an `is_het_non_ref` flag).

For future releases, we need to create this flag before we split multiallelics and then use it downstream.

**Comment by jkgoodrich** [comment]
Running first step to get MT of only variants that need AC and AF fixed:

Code:
```
import hail as hl
hl.init(log='/gnomad_3.1_multi_allelics.log', default_reference='GRCh38')
path = 'gs://gnomad/raw/genomes/3.1/gnomad_v3.1_sparse_unsplit.repartitioned.mt'
mt = hl.read_matrix_table(path)
mt = hl.MatrixTable(
            hl.ir.MatrixKeyRowsBy(
                mt._mir, ["locus", "alleles"], is_sorted=True
            )  # Prevents hail from running sort on genotype MT which is already sorted by a unique locus
        )
SPARSE_ENTRIES = [
    "END",
    "DP",
    "GQ",
    "LA",
    "LAD",
    "LGT",
    "LPGT",
    "LPL",
    "MIN_DP",
    "PID",
    "RGQ",
    "SB",
]
mt = mt.select_entries(*SPARSE_ENTRIES)
mt = mt.annotate_entries(het_non_ref=mt.LGT.is_het_non_ref())
mt = hl.experimental.sparse_split_multi(mt)
info_ht = hl.read_table(
    'gs://gnomad/annotations/hail-0.2/ht/genomes_v3.1/gnomad_genomes_v3.1_info.split.ht'
)
mt = mt.filter_rows(
    (~info_ht[mt.row_key].AS_lowqual)
    & ((hl.len(mt.alleles) > 1) & (mt.alleles[1] != "*"))
)
ht_path = 'gs://gnomad/release/3.0/ht/gnomad.genomes.r3.0.nested.no_subsets.sites.ht' #used v3 for AF
ht = hl.read_table(ht_path)
mt = mt.annotate_rows(AF=ht[mt.row_key].freq[0].AF)
mt = mt.filter_rows((mt.AF > 0.01) & (hl.agg.sum(mt.het_non_ref) >= 1))
mt = mt.checkpoint("gs://gnomad-tmp/gnomad_genomes_v3.1.1_hom_alt_variants_need_fix.mt", overwrite=True)
print("Number of variants:", mt.count_rows())
```

**Comment by jkgoodrich** [comment]
should be fixed by the following PRs and can close this when they go in:  #205 #206

**Comment by jkgoodrich** [comment]
Closing because this has been fixed in the code and there are other tickets referring to the actual gnomAD fix
