### ISSUE TITLE
Standardize release_ht_path for private ht

### ISSUE THREAD

**Issue by mike-w-wilson** [broadinstitute/gnomad_qc#196]
A call to [release_ht_path](https://github.com/broadinstitute/gnomad_qc/blob/9fc7088c6d160f8f0e8c0aea42e18d19a62d8d5c/gnomad_qc/v3/resources/release.py#L34) does not work for version 3.1 and 3.1.1 when public=False. Versions 3 and earlier stored the release ht right after the version directory. Versions 3.1 and 3.1.1 have the private release ht stored within a data_type folder similar to the public versions. Data should be moved or the function updated.

**Comment by nawatts** [comment]
It also won't work with `public=True`. The same issue occurred with the resources objects in gnomad_methods (broadinstitute/gnomad_methods#350). See broadinstitute/gnomad_methods#363 for the fix there.

**Comment by jkgoodrich** [comment]
@nawatts was this all resolved with my most resent resource PR? https://github.com/broadinstitute/gnomad_qc/pull/213 https://github.com/broadinstitute/gnomad_qc/blob/da4ba62eeb5607dd9d50207ea7f227a5094440e2/gnomad_qc/v3/resources/release.py#L43

**Comment by nawatts** [comment]
It looks like #213 addressed [my comment](https://github.com/broadinstitute/gnomad_qc/issues/196#issuecomment-840693516).

I don't know if the original issue of the `data_type` (exomes/genomes) directory was resolved by moving things around in the bucket.

**Comment by nawatts** [comment]
Ah, looks like you resolved the original issue in #191 (specifically in [2c9a978](https://github.com/broadinstitute/gnomad_qc/commit/2c9a978e256e007b1f9dda550989933107803199#diff-655d43af55f527cd4e3b9838c24458b9c44aa192ecec2231951ea7130e242cecR63)).

**Comment by jkgoodrich** [comment]
Great, thank you for looking into in Nick. Closing this issue as it was resolved in #191 (specifically in 2c9a978).
