### ISSUE TITLE
Applying Random Forest Variant QC

### ISSUE THREAD

**Issue by isstafford** [broadinstitute/gnomad_qc#199]
In the supplementary information of a recent gnomAD paper (https://www.nature.com/articles/s41586-020-2308-7), variant QC using a random forest model is described. I'm very interested in using this method on my own data, but the github links in the supplementary do not take me to the code (pages are not found). Is this code still available to share? And is the data used to train this model all openly available?

**Comment by nawatts** [comment]
Hi @isstafford,

This ([broadinstitute/gnomad_qc](https://github.com/broadinstitute/gnomad_qc) is the repository referenced in the paper. The link wasn't working because the code has been reorganized in the time since the paper was published.

**Comment by isstafford** [comment]
Thank you @nawatts, this was really helpful to look at. Unfortunately I'm unable to run anything in hail at this time (something we are looking into for the future). Is it possible to submit variants to gnomAD to have them run through the RF model?

**Comment by nawatts** [comment]
> Is it possible to submit variants to gnomAD to have them run through the RF model?

No, we don't provide services such as this.

As for running Hail, it can be easily installed and run on a workstation/laptop, though how well that would work depends on the size of your dataset. https://hail.is/docs/0.2/getting_started.html

**Comment by isstafford** [comment]
Thanks for your help with this!
