### ISSUE TITLE
Make a README for the sample QC and variant QC annotations

### ISSUE THREAD

**Issue by jkgoodrich** [broadinstitute/gnomad_qc#204]

**Comment by jkgoodrich** [comment]
This is in progress in the following document: https://docs.google.com/document/d/150V4BdZ6_fniLF6tIkRHs5WwK17Rll0iVe3RcZwMsSo/edit

Waiting to finalize the annotation descriptions and structure before the final update to the subsetting code.
   - Martin group OK on HGDP + TGP specific annotations
   - Grace to look over before finalizing

**Comment by gtiao** [comment]
I've read through this document and it's in great shape. Just a few comments and clarifications; and as Julia noted, we're waiting on the Martin group to provide a few HGDP/TGP annotations.

@jkgoodrich Are there any annotation that were included in the gnomAD public release files that were *not* included for this subset? I know the gnomAD PCs are one set, but curious if there are any others.

**Comment by jkgoodrich** [comment]
add age annotation

**Comment by jkgoodrich** [comment]
We are working on looking into differences between the Martin group Kinship estimates and the gnomAD Kinship estimates before deciding on the kinship estimates that we will put on the release sample annotations HT and dense MT and will also be used for the frequency calculations on the variant QC annotations HT and dense MT. More discussion in this Slack thread https://atgu.slack.com/archives/C019RK6U884/p1627910469029300

**Comment by jkgoodrich** [comment]
Relatedness has been resolved, the plan is to move forward with the relatedness estimates from Mary. This includes using her sampling of variants, 20 PCs in the PCA, min_individual_maf = 0.05, and min_kin = 0.05. We are changing the relatedness inference set to include a struct with kin, ibd0, ibd1, and ibd2 for all samples that meet this criteria. I am removing the relationship annotation from that struct and adding an annotation indicating if the sample is removed prior to the frequency calculation -- this annotation will be based on tthe list of related individuals that Mary gave me, which is determined using hl.maximal_independent_set.

**Comment by jkgoodrich** [comment]
@gtiao I have highlighted the regions (new or changed) that I need you to look over in this document: https://docs.google.com/document/d/150V4BdZ6_fniLF6tIkRHs5WwK17Rll0iVe3RcZwMsSo/edit

**Comment by gtiao** [comment]
Made some minor phrasing edits, but otherwise looks good

**Comment by jkgoodrich** [comment]
We have completed the annotation description document
