### ISSUE TITLE
combining sparse_matrix tables

### ISSUE THREAD

**Issue by jjfarrell** [broadinstitute/gnomad_qc#250]
The gnomad blog for 3.1 indicated that a method to combine gvcf sparse matrixes was developed to solve the n+1 joint-genotyping problem.  Is there an example or some documentation on how combining sparse matrixes is done?

**Comment by ch-kr** [comment]
Hello! The hail [forum](https://discuss.hail.is/) is likely a more appropriate location for this question. These links from the hail docs might also be helpful: VCF [combiner](https://hail.is/docs/0.2/experimental/vcf_combiner.html#vcf-combiner) and their new [VariantDataset ](https://hail.is/docs/0.2/vds/index.html) data format.
