### ISSUE TITLE
max_r_het_hom_var

### ISSUE THREAD

**Issue by wym0072003** [broadinstitute/gnomad_qc#281]
Hi,

I have a quick question on the cutoff of 'max_r_het_hom_var'. Why did you set it to 3.3 but not 2 or below based on MAD and median values in the cohort? Thanks.

Best,

Ming

**Comment by ch-kr** [comment]
Hi Ming,

Could you clarify your question? Are you asking about the cutoffs for a particular version of gnomAD?

Thanks!

**Comment by ch-kr** [comment]
Hi Ming -- I am going to close this ticket, but you can reopen it if you have additional comments.
