### ISSUE TITLE
Document tabix as part of making the release

### ISSUE THREAD

**Issue by nawatts** [broadinstitute/gnomad_qc#29]
Add step in readme and document how to run tabix in the cloud.

**Comment by gtiao** [comment]
+1 to this!

**Comment by nawatts** [comment]
This is very similar to one of the sample use cases for the Google Genomics Pipelines API

https://github.com/googlegenomics/pipelines-api-examples/tree/master/samtools

**Comment by nawatts** [comment]
No longer needed since `hl.export_vcf` can now output tabix indices.
