### ISSUE TITLE
Generate code for calculating allele frequencies

### ISSUE THREAD

**Issue by mike-w-wilson** [broadinstitute/gnomad_qc#310]
https://github.com/broadinstitute/gnomad_qc/pull/335

6/1 Update:
Hail cannot run the number of aggregations we need on the full densified dataset. This is an issue with the way the Java code is being built and run. To get around this, we need to rewrite the frequency code to split the samples of the dataset into n parts by some boolean annotation. We'll run frequency on each part and then sum the parts.

**Comment by mike-w-wilson** [comment]
I believe we need to address this: https://atgu.slack.com/archives/CRA2TKTV0/p1598031656007300        
Also from the v3 code:
>  # NOTE: Using previous callset AF works for small incremental changes to a callset, but we will need to revisit for large increments # noqa

**Comment by mike-w-wilson** [comment]
Retrieving haplotype caller version to help with decision in #312

**Comment by mike-w-wilson** [comment]
Qin and I met to review freq code and determine what tools we want to use for pair programming

**Comment by mike-w-wilson** [comment]
Hitting a hail bug when generating  high AB het annotation per group after annotate_freq -- Tim is looking inot it: https://hail.zulipchat.com/#narrow/stream/123010-Hail-Query-0.2E2-support/topic/.E2.9C.94.20Summing.20number.20of.20entries.20meeting.20criteria.20.20by.20group/near/346939411

**Comment by KoalaQin** [comment]
add FAF and popmax function to the code.

**Comment by mike-w-wilson** [comment]
I moved the original freq epic from gnomad_qc to gnomad_prod and zenhub is having trouble finding it to link it. https://github.com/broadinstitute/gnomad_production/issues/934 It looks like git dropped all the original dependencies which is unfortunate but hopefully just part of their ongoing issues today and the dependencies will come back soon
