### ISSUE TITLE
HGDP+1KG numbers dont add up 

### ISSUE THREAD

**Issue by jerome-f** [broadinstitute/gnomad_qc#315]
Hi,

I am noticing a small discrepancy in numbers from the data reported in the main [paper](https://www.biorxiv.org/content/10.1101/2023.01.23.525248v2.full): N=4096 and unrelated N =3378,
but in the meta data file N=4097 and unrelated N = 3380 ? Could you let me know if this is correct? here is my code:
```
import pandas as pd
import json as js
import numpy as np
df = pd.read_csv("gnomad.genomes.v3.1.2.hgdp_1kg_subset_sample_meta.tsv",sep='\t')
df.drop(index=0,inplace=True) #deleting the QC sample CHMI_CHMI3_WGS2
df = df[df.high_quality].copy() #Drop all samples failing quality filter
df['related'] = df.relatedness_inference.apply(lambda x: js.loads(x)['related'])
df.reset_index(drop=True,inplace=True)
print(np.sum(~df.related))
```

I also noticed the the Table S3 in SI also has a discrepancy:
_Unrelated individuals 807 2,507 3,378_
807 + 2507 is 3314

**Comment by ch-kr** [comment]
Hi,

Thanks for reaching out to us. Questions about the HGDP/1KG paper should be directed to the corresponding author, Alicia Martin ([armartin@broadinstitute.org](mailto:armartin@broadinstitute.org)).

In general, questions or feedback about the gnomAD dataset should be directed to [gnomad@broadinstitute.org](mailto:gnomad@broadinstitute.org); GitHub issues should be limited to code-related questions or feedback.
