### ISSUE TITLE
Update README documentation for v2 and v3 subfolders

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad_qc#51]
The top-level README in this repo refers to v2.1, and should probably go into the v2 subfolder. v3 has no high-level README documentation yet, but we should write this for the public

**Comment by nawatts** [comment]
@jkgoodrich did #208 resolve this?

**Comment by jkgoodrich** [comment]
Oh, yes it does, thanks for finding Nick!

This is resolved by #208
