### ISSUE TITLE
Create script to generate all sites AN file

### ISSUE THREAD

**Issue by mike-w-wilson** [broadinstitute/gnomad_qc#545]
The script needs to generate the new AN file resource. We need to confirm that the group membership used to create the table matches the release. Group membership HTs were created for nonukb and ukb separately which includes all groups and downsamplings.

**Comment by jkgoodrich** [comment]
PR's in [gnomad_qc](https://app.zenhub.com/workspaces/gnomad-5f4d127ea61afc001d6be50b/issues/gh/broadinstitute/gnomad_qc/550) and [gnomad_methods](https://app.zenhub.com/workspaces/gnomad-5f4d127ea61afc001d6be50b/issues/gh/broadinstitute/gnomad_methods/669) merged
