### ISSUE TITLE
Question about the segmental duplication file

### ISSUE THREAD

**Issue by wavefancy** [broadinstitute/gnomad_qc#56]
Dear Developers,

I want to follow some variant and sample QC as the gnomAD project. Looking at the segmental duplication file `gs://gnomad-public/intervals/hg19_self_chain_split_both.bed`, which is different from the one from UCSC or [Washington U](http://humanparalogy.gs.washington.edu/build38/data/). Could you please explain this a little bit where this file coming from? 

By the way, do you have the hg38 version of decoy region? `gs://gnomad-public/intervals/mm-2-merged.GRCh37_compliant.bed`

Thank you very much for your help.

Best regards
Wallace

**Comment by nawatts** [comment]
Hi @wavefancy. Information about the segmental duplication file can be found on https://gnomad.broadinstitute.org/help/vep.
