### ISSUE TITLE
Unscramble TOPMed sample swaps

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad_qc#62]

**Comment by gtiao** [comment]
Notes from Google Doc:

- Swap on loading for now, but re-write in MT for N+K callset
- We need to track this in the meta table: use new IDs in `s` but keep extra annotation for old ID (for tracking purposes)

**Comment by jkgoodrich** [comment]
Added to the following PR https://github.com/broadinstitute/gnomad_meta/pull/1/files
