### ISSUE TITLE
Make major subsets

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad_qc#63]

**Comment by gtiao** [comment]
Notes from Google Doc:

- non-v2
- v2-but-non-v3
- non-topmed: all TOPMed samples have a Collaborator Sample ID with prefix NWD 
- non-cancer - check with Laurent, but likely just anything not TCGA
- controls
- non-neuro

**Comment by gtiao** [comment]
Creating subsets means creating the AC/AF/AN/n_homalt arrays for all the different cohorts above. (Possibly also stratified by sex and pop/subpop -- to be discussed)

This code should go into the script where we generate frequencies for gnomAD overall (after population and sex inference)

**Comment by gtiao** [comment]
Discussion with Laurent on these subsets:

LF: so in general, it is quite nice to have the possibility of adding non-overlapping v2 and v3 data together to produce the largest possible dataset
LF: because v3-non-v2 + v2 == v3 + v2-non-v3, I think the idea was to only generate the v3-non-v2 data so that there is no reprocessing of the v2 data necessary

So we won't be doing v2-non-v3, just v3-non-v2; and Laurent confirms that non-cancer == non-TCGA

**Comment by nawatts** [comment]
This looks like it's referring to v3. Is there anything left to be done for this?

**Comment by jkgoodrich** [comment]
Not that I can think of. 

This was performed for v3.1 and the relevant code is [here](https://github.com/broadinstitute/gnomad_qc/blob/master/gnomad_qc/v3/annotations/generate_freq_data.py)
