### ISSUE TITLE
Remove ~100 samples from the AFib cohort containing three deltaF508 homozygotes

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad_qc#65]

**Comment by gtiao** [comment]
Notes from Google Doc:

- Look at the genotypes (there was an enrichment of cystic fibrosis patients in this cohort). research_project: CCDG_Atrial_Fibrillation_Duke 
- Add a sample QC check for number of P/LP ClinVar alleles per individual to see if there are cohorts with a substantial excess
- Place a hard filter up front for these

**Comment by gtiao** [comment]
Kat added: `research_project: CCDG_Atrial_Fibrillation_Duke`

**Comment by jkgoodrich** [comment]
Added to the following PR https://github.com/broadinstitute/gnomad_meta/pull/1/files
