### ISSUE TITLE
Create dictionary explaining what the fields are in the release files (HT, VCF)

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad_qc#66]

**Comment by jkgoodrich** [comment]
This is dependent on finalizing the readme for the HGDP + 1KG subset which can be reused for this ticket. #204

**Comment by jkgoodrich** [comment]
#204 has been closed and that was specific to HGDP + 1KG. For HGDP + 1KG we have this in the globals and will also have a link on the downloads page to the descriptions specific to that subset. There is a lot of overlap for this and those defined for the HGDP + 1KG subset, but what is the plan for the full dataset release? Should we add a README to the release folder (would need one for the VCF and one for the HT) or also a link on the downloads page, or both?

**Comment by gtiao** [comment]
Duplicate with ticket #368
