### ISSUE TITLE
Collect all project-level annotations available for v3.1

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad_qc#73]

**Comment by gtiao** [comment]
Releasable vs non-releasable
Subset status (case vs. control, TOPMed, cancer, etc.)
Any available phenotype data: age

**Comment by ytarasov-broad** [comment]
Project level annotations complete and can be found in the v3 callset spreadsheet. Sample level annotations with all available info as of 202-09-18 is also complete. Waiting to hear back from a few more PIs for additional samples which will be added if they are sent by 2020-09-28.
