### ISSUE TITLE
Export sites (HT to VCF) to hand off to Laura for VQSR

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad_qc#76]

**Comment by gtiao** [comment]
Ideally we would have two runs: one standard AS_VQSR, and one with transmitted singletons (AS_VQSR_TS)

**Comment by jkgoodrich** [comment]
Blocked because of: https://discuss.hail.is/t/out-of-memory-in-allele-specific-and-site-level-info-calculation-on-a-sparse-matrix-table/1660
