### ISSUE TITLE
Compare UKBB variant RF on gnomAD with gnomAD variant RF on UKBB

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad_qc#84]

**Comment by gtiao** [comment]
Is this task still relevant/needed?

**Comment by jkgoodrich** [comment]
I think maybe this was because when we have the gnomAD v4 variant QC, if RF looks good, we might want to see how well the UKB model would perform on the gnomAD v4 data and how well the a full training (or maybe even a training without the UKB data) performs on just the UKB data?

**Comment by ch-kr** [comment]
closing because of Julia's comment ("if RF looks good") -- we chose AS VQSR for v4
