### ISSUE TITLE
Review current set of sanity checks for VCF

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad_qc#88]
..."That metrics for non-PAR chrX variants in male samples are 0"

**Comment by gtiao** [comment]
Also ensure VCF export has LOFTEE annotations (include in VCF validation)

**Comment by gtiao** [comment]
Add VEP field check

**Comment by gtiao** [comment]
See also fields missing "Descriptions", reported by a user: https://atgu.slack.com/archives/CNL7NA6H2/p1599773983002300

**Comment by gtiao** [comment]
Please update sanity checks based off KC's checks (written for UKBB), as they are nicely set up there and will be very similar

**Comment by mike-w-wilson** [comment]
VCF field checks were modelled on UKBB. All fields confirmed they had a description. VEP was moved to INFO and reconfigured. LOF annotations are present. Chr20 ran successfully on GATK ValidateVariants tool to validate the VCF formatting.  Non standard contigs were removed from hail's GRCh38 to create a custom assembly "gnomAD_GRCh38" which is simply the standard contigs 1-22,X,Y, and M.
