### ISSUE TITLE
Revise ancestry inference in pipeline to run on representative set of diverse samples; and project the rest

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad_qc#93]

**Comment by ch-kr** [comment]
We did this for v4 MVP -- we tried to select diverse samples from HGDP/1KG and select projects (e.g., MID samples) to use for v4 genetic ancestry inference. We realized as part of this process that we weren't including enough representation of other populations and were moving a lot of samples that had previous labels into the "remaining" category, particularly for NFEs
