### ISSUE TITLE
Add callrate computation to sample QC

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad_qc#96]
Notes from Laurent:

- callrate may be tricky in that our QC MT is typically filtered for variant callrate > 99% ==> does this make callrate useless if computed  on this? If so, how can we compute this efficiently (this requires densifying) and fairly w.r.t. platforms?

**Comment by ch-kr** [comment]
we now calculate callrate prior to calculating the QC MT, so this is no longer relevant
